modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="ndt_mod"
version="1.0.0"
displayName="NDT Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Creep, MCreator"

[[dependencies.ndt_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




